config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  concern :likeable do
    resources :likes, only: %i[create destroy]
  end

  resources :posts, shallow: true, concerns: :likeable do
    resources :comments, concerns: :likeable
  end

  resources :users, only: %i[index show], shallow: true do
    resources :requests, only: %i[index create update destroy]
  end

  delete 'users/:id', to: 'users#destroy'
  get 'search', to: 'users#search'
  get 'notifications', to: 'notifications#index'
  get 'requests', to: 'requests#index'
  get 'users/:id/requests', to: redirect('/requests')
  get 'credits', to: 'static_pages#credits'
  get 'privacy', to: 'static_pages#privacy'
  root 'posts#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Notifiable

  belongs_to :post, counter_cache: true
  belongs_to :user, counter_cache: true

  has_many :likes, as: :likeable, dependent: :destroy
  has_many :notifications, as: :notifiable, dependent: :destroy
  has_rich_text :content

  validates_with RichContentValidator
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[show edit update destroy]
  before_action :set_parent, only: %i[index new create]
  before_action :authenticate_user!

  def index
    @comments = @post.comments
  end

  def new
    @comment = @post.comments.build
    @comment.user_id = current_user.id
  end

  def edit
    return unless @comment.user.id == current_user.id

    render :edit
  end

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.turbo_stream { flash.now[:notice] = 'Comment added!' }
        format.html { redirect_to :root, notice: 'Comment added!' }

        @comment.notify
        @comment.broadcast_append_to 'updates_feed',
                                     locals: { comment: @comment, current_user: current_user, actions: :off },
                                     target: "post_#{@comment.post.id}_comments"
      else
        message = "Comment #{@comment.errors.full_messages.join('').downcase}"
        flash.now[:alert] = message
        format.turbo_stream { render :new, status: :unprocessable_entity }
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    return unless @comment.user.id == current_user.id

    respond_to do |format|
      if @comment.update(comment_params)
        format.turbo_stream { flash.now[:notice] = 'Comment updated!' }
        format.html { redirect_to :root, notice: 'Comment updated!' }
      else
        message = "Comment #{@comment.errors.full_messages.join('').downcase}"
        flash.now[:alert] = message
        format.turbo_stream { render :edit, status: :unprocessable_entity }
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    return unless @comment.user.id == current_user.id

    @comment.destroy

    respond_to do |format|
      format.html { redirect_to :root, notice: 'Comment deleted!' }
      format.turbo_stream { flash.now[:notice] = 'Comment deleted!' }
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_parent
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:content, :post_id, :user_id)
  end
end

app/views/comments/_comment.html.erb
<%= turbo_frame_tag dom_id(comment) do%>
<% actions ||= :on %>
  <div class="c-comment"> 
    <div class="c-comment__header">
      <div class="c-comment__badge">
        <%= render 'users/badge', owner: comment.user %>
      </div>
      <% if current_user == comment.user && actions == :on %>
        <div class="c-comment__actions">
          <% if current_user.id == comment.user.id %>
            <%= link_to 'Edit', edit_comment_path(comment), data: { turbo_frame: "#{dom_id(comment)}_text" }, class: 'link' %>
            <%= link_to 'Delete', comment_path(comment), data: { turbo_frame: dom_id(comment), turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'link' %>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="c-comment__content">      
      <%= turbo_frame_tag "#{dom_id(comment)}_text" do %>
        <%= comment.content %>
      <% end %>
    </div>
    <div class="c-comment__status">
      <%= turbo_frame_tag "#{dom_id(comment)}_likes" do %>
          <% if current_user.already_liked?(comment) %>
            <%= link_to 'Unlike', like_path(comment, like: { likeable_id: comment.id, likeable_type: 'Comment' }), data: { turbo_method: :delete }, class: 'link' %>
          <% else %>
            <%= link_to 'Like', comment_likes_path(comment, like: { liked_by: current_user.id, likeable_id: comment.id, likeable_type: 'Comment' }), data: { turbo_method: :post }, class: 'link' %>
          <% end %>
          <span>Likes: <%= comment.likes.size %> </span>
        <% end %>
    </div>
  </div>
<% end %>

app/views/comments/_editform.html.erb
<%= form_with model: @comment do |form| %>
  <%= form.rich_text_area :content,
                     required: true,
                     id: "#{dom_id(@comment)}_edit" %>
  <%= form.submit %>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: Comment.new,
              url: post_comments_path(post),
              data: { controller: 'reset-form', action: 'turbo:submit-end->reset-form#reset' } do |form| %>
  <%= form.rich_text_area :content,
                     placeholer: "Add a comment...",
                     required: true,
                     id: "#{dom_id(post)}_comment_input" %>
  <%= form.submit %>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.append "#{dom_id(@post)}_comments", @comment %>
<%= turbo_stream.prepend "flash", partial: 'layouts/flash' %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove @comment %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= turbo_frame_tag "#{dom_id(@comment)}_text" do %>
  <%= render 'comments/editform' %>
<% end %>

app/views/comments/edit.turbo_stream.erb
<%= render_turbo_flash %>

app/views/comments/index.html.erb
<% @comments.each do |comment| %>
  <%= turbo_frame_tag dom_id(comment) do %>
    <%= render 'comments/comment', comment: comment %>
  <% end %>
<% end %>

app/views/comments/new.turbo_stream.erb
<%= render_turbo_flash %>

app/views/comments/update.turbo_stream.erb
<%= render_turbo_flash %>
<%= turbo_stream.update @comment %>