config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  concern :likeable do
    resources :likes, only: %i[create destroy]
  end

  resources :posts, shallow: true, concerns: :likeable do
    resources :comments, concerns: :likeable
  end

  resources :users, only: %i[index show], shallow: true do
    resources :requests, only: %i[index create update destroy]
  end

  delete 'users/:id', to: 'users#destroy'
  get 'search', to: 'users#search'
  get 'notifications', to: 'notifications#index'
  get 'requests', to: 'requests#index'
  get 'users/:id/requests', to: redirect('/requests')
  get 'credits', to: 'static_pages#credits'
  get 'privacy', to: 'static_pages#privacy'
  root 'posts#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, omniauth_providers: %i[github google_oauth2]

  after_create :send_welcome_email

  validates :name, presence: true
  validates :email, uniqueness: true
  validates :email, presence: true
  validates :email, format: Devise.email_regexp

  has_many :sent_requests,
           foreign_key: :user_id,
           class_name: :Request,
           dependent: :destroy

  has_many :received_requests,
           foreign_key: :friend_id,
           class_name: :Request,
           dependent: :destroy

  has_many :friends_sent, -> { merge(Request.accepted) }, through: :sent_requests, source: :friend
  has_many :friends_rec, -> { merge(Request.accepted) }, through: :received_requests, source: :user
  has_many :pending_friends_sent, -> { merge(Request.pending) }, through: :sent_requests, source: :friend
  has_many :pending_friends_rec, -> { merge(Request.pending) }, through: :received_requests, source: :user

  has_many :likes, foreign_key: :liked_by, dependent: :destroy
  has_many :notifications, foreign_key: :target_id, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one_attached :avatar

  def friends
    friends_sent + friends_rec
  end

  def pending_friends
    pending_friends_sent + pending_friends_rec
  end

  def all_friends
    friends + pending_friends
  end

  def find_request(other)
    return nil if other == self

    Request.find_by(friend: other, user: self) || Request.find_by(user: other, friend: self)
  end

  def already_liked?(resource)
    likes.pluck(:likeable_type, :likeable_id).include?([resource.class.name, resource.id])
  end

  def profile_picture(size: 100)
    if avatar.attached?
      avatar.variant(resize_to_limit: [size, size])
    elsif external_picture
      external_picture
    else
      'default_pic.png'
    end
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    unless user
      user = User.create(name: data['name'],
                         email: data['email'],
                         external_picture: data['image'],
                         password: Devise.friendly_token[0, 20])
    end
    user
  end

  protected

  def send_welcome_email
    UserMailer.with(user: self).welcome_email.deliver_later
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end

  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Github'
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.github_data"] = request.env["omniauth.auth"].except(:extra)
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show destroy]
  before_action :authenticate_user!

  # GET /users
  def index
    @results = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  def edit
    @user = current_user
    render 'profile'
  end

  def update
  end

  # GET /search
  def search
    raise 'No search term' unless params[:query].present?

    @param = params[:query].downcase
    @results = User.where('lower(name) LIKE :query', query: "%#{@param}%").order(id: :asc)
  end

  # DELETE /users/1
  def destroy
    if @user.id == 1
      redirect_to root_path, notice: "Can't delete user.", status: 400 and return
    end

    @user.destroy
    reset_session
    redirect_to new_user_session_path, notice: "Account deleted.", status: 303
  end

  private

  # Set user before show action
  def set_user
    if params[:id].present?
      @user = User.find(params[:id])
    else
      @user = current_user
    end
  end
end

app/views/users/_badge.html.erb
<div class="c-badge">
  <span class="c-badge__image">
    <%= image_tag owner.profile_picture(size: 30) %>
  </span>
  <span class="c-badge__name"><%= link_to owner.name, user_path(owner), data: { turbo: false } %></span>
</div>

app/views/users/_list_user.html.erb
<div class="l-results">
  <ul class="l-results__list">
    <% @results.each do |result| %>
      <li><%= link_to result.name, user_path(result), class: 'link link--no-pad' %>
      <% unless current_user.all_friends.include?(result) || current_user == result %>
        <%= turbo_frame_tag "request_#{dom_id(result)}" do %>
          <%= link_to 'Send request', user_requests_path(current_user, request: { friend_id: result} ), data: { 'turbo-method': :post }, class: 'link' %></li>
        <% end %>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/users/_profile.html.erb
<div class="c-profile">
  <div class="c-profile__image">
    <%= image_tag user.profile_picture(size: 150), class: 'image-large' %>
  </div>
  <div class="c-profile__details">
    <span class="large"><%= user.name %></span>
    <span>Member for <%= distance_of_time_in_words_to_now(user.created_at) %>.</span>
    <span>Gender Identity: <%= user.gender %></span>
    <% if user.birthday %>
      <span>Birthday: <%= user.birthday.to_fs(user.show_birth_year ? :long_ordinal : :short_ordinal) %></span>
    <% end %>
    <% if user.website %>
      <span>Website: <%= link_to user.website %></span>
    <% end %>
    <% if user.location %>
      <span>Location: <%= user.location %></span>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="l-users">
  <h2>All users</h2>

  <%= render 'list_user' %>
</div>

app/views/users/search.html.erb
<div class="l-users">
  <h2>Results</h2>

  <%= render 'list_user' %>
</div>

app/views/users/show.html.erb
<div class='l-profile'>
  <div class='l-profile__request'>
    <% unless current_user.all_friends.include?(@user) || current_user == @user %>
      <%= turbo_frame_tag "request_#{dom_id(@user)}" do %>
        You are not friends! <%= link_to 'Send request', user_requests_path(current_user, request: { friend_id: @user} ), data: { 'turbo-method': :post }, class: 'link' %></li>
      <% end %>
    <% end %>
  </div>
  <div class="l-profile__detail">
    <%= render 'users/profile', user: @user %>
  </div>
  <div class='l-profile__posts'>
    <h3><%= @user.name %>'s Posts</h3>
    <% @user.posts.includes(:user, :rich_text_content).each do |post| %>
      <%= render post %>
    <% end %>
  </div>
</div>