config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  concern :likeable do
    resources :likes, only: %i[create destroy]
  end

  resources :posts, shallow: true, concerns: :likeable do
    resources :comments, concerns: :likeable
  end

  resources :users, only: %i[index show], shallow: true do
    resources :requests, only: %i[index create update destroy]
  end

  delete 'users/:id', to: 'users#destroy'
  get 'search', to: 'users#search'
  get 'notifications', to: 'notifications#index'
  get 'requests', to: 'requests#index'
  get 'users/:id/requests', to: redirect('/requests')
  get 'credits', to: 'static_pages#credits'
  get 'privacy', to: 'static_pages#privacy'
  root 'posts#index'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, counter_cache: true
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :comments, dependent: :destroy, inverse_of: :post
  has_rich_text :content

  validates_with RichContentValidator
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[edit update destroy]
  before_action :authenticate_user!

  def index
    query_ids = [current_user.id] + current_user.friends_sent_ids + current_user.friends_rec_ids
    @posts = Post.includes([:user, { user: :avatar_attachment }]).where(user_id: query_ids).order(id: :desc)
  end

  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
    if @post.user.id == current_user.id
      render :edit
    else
      redirect_to :root, alert: "Not authorized to edit another user's posts."
    end
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.turbo_stream { flash.now[:notice] = 'Post added!' }
        format.html { redirect_to :root, notice: 'Post added!' }

        @post.broadcast_prepend_to 'updates_feed',
                                   locals: { post: @post, current_user: current_user, actions: :off },
                                   target: 'post_feed'
      else
        message = "Post #{@post.errors.full_messages.join('').downcase}"
        flash.now[:alert] = message
        format.turbo_stream { render :new, status: :unprocessable_entity }
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    return unless @post.user.id == current_user.id

    respond_to do |format|
      if @post.update(post_params)
        format.turbo_stream { flash.now[:notice] = 'Post updated!' }
        format.html { redirect_to :root, notice: "Post updated!" }
      else
        message = "Post #{@post.errors.full_messages.join('').downcase}"
        flash.now[:alert] = message
        format.turbo_stream { render :edit, status: :unprocessable_entity }
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    return unless @post.user.id == current_user.id

    @post.destroy

    respond_to do |format|
      format.html { redirect_to :root, notice: "Post was successfully removed." }
      format.turbo_stream { flash.now[:notice] = 'Post removed!' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Strong parameters
  def post_params
    params.require(:post).permit(:content)
  end
end

app/views/posts/_empty.html.erb
<div class="empty-state">
  <p class="empty-state__text">
    No posts here... yet. Make some friends to see their posts!
  </p>
  <p>You can use the search box above to find your friends, or <%= link_to 'see all current users', users_path %>.</p>
  <br>
  Want to check the app out? Try logging in with these credentials:<br>
  <ul>
    <li>email: <span class="empty-state__code">test1@test.com</span></li>
    <li>password: <span class="empty-state__code">password</span></li>
  </ul>
</div>

app/views/posts/_form.html.erb
<%= form_with model: @post || Post.new, data: { controller: 'reset-form', action: 'turbo:submit-end->reset-form#reset' } do |form| %>
  <%= form.rich_text_area :content,
                     placeholder: "What's on your mind? Drag and drop images are supported.",
                     required: true,
                     id: "#{@post.present? ? dom_id(@post) : dom_id(Post.new)}_form" %>
  <%= form.submit %>
<% end %>

app/views/posts/_post.html.erb
<%= turbo_frame_tag dom_id(post) do %>
<% actions ||= :on %>
  <div class="c-post">
    <div class="c-post__header">
      <div class="c-post__badge">
        <%= render 'users/badge', owner: post.user %>
      </div>
      <% if current_user == post.user && actions == :on %>
        <div class="c-post__actions">
          <% if current_user.id == post.user.id %>
            <%= link_to 'Edit', edit_post_path(post), data: { turbo_frame: "#{dom_id(post)}_content" }, class: 'link' %>
            <%= link_to 'Delete', post_path(post), data: { turbo_frame: dom_id(post), turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'link' %>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="c-post__content">
      <%= turbo_frame_tag "#{dom_id(post)}_content" do %>
        <%= post.content %>
      <% end %>
    </div>
    <div class="c-post__status">
      <%= turbo_frame_tag "#{dom_id(post)}_likes" do %>
        <% if current_user.already_liked?(post) %>
          <%= link_to 'Unlike', like_path(post, like: { likeable_id: post.id, likeable_type: 'Post'} ), data: { turbo_method: :delete }, class: 'link' %>
        <% else %>
          <%= link_to 'Like', post_likes_path(post, like: {liked_by: current_user.id, likeable_id: post.id, likeable_type: 'Post'}), data: { turbo_method: :post }, class: 'link' %>
        <% end %>
        <span>Likes: <%= post.likes.size %> </span>
      <% end %>
    </div>
    <div class="c-post__responses">
      <%= turbo_frame_tag "#{dom_id(post)}_comments" do %>
        <% post.comments.includes([:user, :rich_text_content, {user: :avatar_attachment }]).each do |comment| %>
          <%= render 'comments/comment', comment: comment %>
        <% end %>
      <% end %>
    </div>
    <div class="c-post__input">
      <%= render 'comments/form', post: post %>
    </div>
  </div>
<% end %>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.prepend "post_feed", @post %>
<%= turbo_stream.prepend "flash", partial: 'layouts/flash' %>

app/views/posts/destroy.turbo_stream.erb
<%= turbo_stream.remove @post %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= turbo_frame_tag "#{dom_id(@post)}_content" do %>
  <%= render 'posts/form' %>
<% end %>

app/views/posts/edit.turbo_stream.erb
<%= render_turbo_flash %>

app/views/posts/index.html.erb
<div class="l-new_post">
  <%= render 'posts/form' %>
</div>
<div class="l-feed">
  <%= turbo_frame_tag 'post_feed' do %>
    <%= render "posts/empty" %>
    <% @posts.includes(:rich_text_content).each do |post| %>
      <%= render 'posts/post', post: post %>
    <% end %>
  <% end %>
</div>

app/views/posts/new.turbo_stream.erb
<%= render_turbo_flash %>

app/views/posts/update.turbo_stream.erb
<%= render_turbo_flash %>
<%= turbo_stream.update @post %>