config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  concern :likeable do
    resources :likes, only: %i[create destroy]
  end

  resources :posts, shallow: true, concerns: :likeable do
    resources :comments, concerns: :likeable
  end

  resources :users, only: %i[index show], shallow: true do
    resources :requests, only: %i[index create update destroy]
  end

  delete 'users/:id', to: 'users#destroy'
  get 'search', to: 'users#search'
  get 'notifications', to: 'notifications#index'
  get 'requests', to: 'requests#index'
  get 'users/:id/requests', to: redirect('/requests')
  get 'credits', to: 'static_pages#credits'
  get 'privacy', to: 'static_pages#privacy'
  root 'posts#index'
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div class="l-flash__message l-flash__message-<%= flash_type %>"
      data-controller='toggle-display'
      data-action='animationend->toggle-display#hide'
  >
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<span>&copy; <%= Date.today.year %> Simmon Li</span>
<span><%= link_to 'About', 'https://crespire.dev/' %></span>
<span><%= link_to 'Credits', credits_path %></span>

app/views/layouts/_nav.html.erb
<nav class="l-header__nav">
  <div class="l-header__search">
    <%= render 'layouts/search' if user_signed_in? %>
  </div>
  <div class="l-header__links">
    <%= link_to 'Home', root_path, class: 'link' %>
    <%= link_to 'Users', users_path, class: 'link' %>
    <% if user_signed_in? %>
      <span>Hello, <%= link_to current_user.name, edit_user_registration_path, class: 'link link--no-pad' %>!</span>
      <%= turbo_frame_tag "#{dom_id(current_user)}_notify_count" do %>
        <%= link_to "Notifications (#{current_user.notifications.unseen.size})", notifications_path, data: { turbo: false }, class: 'link' %>
      <% end %>
      <%= link_to 'Requests', requests_path, class: 'link' %>
      <%= button_to 'Log Out', destroy_user_session_path, method: :delete, data: { turbo: false } %>
    <% end %>
  </div>
</nav>

app/views/layouts/_search.html.erb
<%= form_with url: '/search', method: :get do |form| %>
  <%= form.label :query, 'Search:' %>
  <%= form.text_field :query, placeholder: 'Username...', required: true %>
  <%= form.submit 'Go!' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="l-container">
    <%= turbo_stream_from 'updates_feed' if user_signed_in? %>
    <header class="l-header">
      <%= render 'layouts/nav' %>
      <% if user_signed_in? %>
        <%= turbo_stream_from current_user, 'notifications' %>
      <% end %>
    </header>
    <div id="flash" class="l-flash">
      <%= render 'layouts/flash' %>
    </div>
    <main class="l-main">
      <%= yield %>
    </main>
    <footer class="l-footer">
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>